const state={style:null,schema:null,nonce:null,slots:{PROD:{label:'PROD',selected:true},A:{label:'A',selected:true},B:{label:'B',selected:false},C:{label:'C',selected:false}},controls:{}};
const $=id=>document.getElementById(id);
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{}),...(opts.method?{'X-Amadeus-CSRF':state.nonce}: {})}});const b=await r.json();if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function updatePreview(){const base=$('baseline').value,delta=$('delta').value;$('effective').value=base+delta}
function renderControls(){ $('controls').replaceChildren(...state.schema.controls.map(c=>{const d=document.createElement('div');d.className='control';d.innerHTML=`<label><span>${c.id}</span><span>${c.safeMin}–${c.safeMax}</span></label><input data-control="${c.id}" type="number" min="${c.safeMin}" max="${c.safeMax}" step="${c.step}" placeholder="inherit production/model default"><small>${c.description}</small>`;return d}));state.controls={};document.querySelectorAll('[data-control]').forEach(i=>{state.controls[i.dataset.control]=i;i.addEventListener('input',()=>renderSlots())})}
function currentOptions(){const out={};for(const [k,i] of Object.entries(state.controls))if(i.value!=='')out[k]=k==='top_k'||k==='max_new_tokens'||k==='seed'?Number.parseInt(i.value,10):Number(i.value);return out}
function renderSlots(){const box=$('slots');box.replaceChildren(...Object.values(state.slots).map(s=>{const d=document.createElement('div');d.className='slot'+(s.selected?' selected':'');const h=document.createElement('h3');h.textContent=s.label;d.append(h);const p=document.createElement('p');p.textContent=s.label==='PROD'?'Read-only current production snapshot':`Candidate ${s.label} · ${$('emotion').value} · ${$('baseline').value.length+$('delta').value.length} style chars`;d.append(p);const cb=document.createElement('input');cb.type='checkbox';cb.checked=s.selected;cb.setAttribute('aria-label',`select ${s.label}`);cb.addEventListener('change',()=>{s.selected=cb.checked;renderSlots()});d.append(cb);if(s.label!=='PROD'){const clone=document.createElement('button');clone.textContent='Clone PROD';clone.addEventListener('click',()=>{s.baseline=state.style.baseline;s.delta=state.style.emotions[$('emotion').value].instruct;s.options={};renderSlots()});d.append(clone)}return d}));$('compareState').textContent=`${Object.values(state.slots).filter(s=>s.selected).length} selected · mode ${$('mode').value}`}
function fillEmotion(){const e=$('emotion').value;const item=state.style.emotions[e];$('baseline').value=state.style.baseline;$('delta').value=item.instruct;updatePreview();renderSlots()}
async function generate(){const candidates=Object.values(state.slots).filter(s=>s.selected).map(s=>({slot:s.label,emotion:$('emotion').value,baseline:$('baseline').value,delta:$('delta').value,options:currentOptions()}));try{const b=await api('/api/v1/synthesize',{method:'POST',body:JSON.stringify({text:$('text').value,format:'wav',candidates})});renderResults(b.results);$('health').textContent='lab ready';}catch(e){$('results').innerHTML=`<p class="error">${e.message}</p>`}}
function renderResults(items){$('results').replaceChildren(...items.map(x=>{const d=document.createElement('div');d.className='result';d.innerHTML=`<div><b>${x.slot} · ${x.emotion}</b> <small>${x.styleHash.slice(0,12)} · ${x.durationMs}ms · wall ${x.wallMs}ms · RTF ${x.rtf}</small><audio controls preload="none" src="${x.audioUrl}"></audio></div><div><small>queue ${Number(x.timing.queueWaitMs||0).toFixed(1)}ms<br>prefill ${x.timing.prefillMs??'—'}ms<br>generation ${x.timing.generationMs??'—'}ms<br>decode ${x.timing.decodeMs??'—'}ms</small></div>`;return d}))}
async function saveDraft(){try{const b=await api('/api/v1/drafts',{method:'POST',body:JSON.stringify({emotion:$('emotion').value,baseline:$('baseline').value,delta:$('delta').value,options:currentOptions(),textChars:$('text').value.length})});$('health').textContent=`draft ${b.id.slice(0,8)} saved`}catch(e){$('health').textContent=e.message}}
async function createProposal(){try{const b=await api('/api/v1/proposals',{method:'POST',body:JSON.stringify({expectedProductionStyleHash:state.styleHash,candidate:{emotion:$('emotion').value,baseline:$('baseline').value,delta:$('delta').value,generationOverrides:currentOptions()}})});$('health').textContent=`proposal ${b.id.slice(0,8)} created`}catch(e){$('health').textContent=e.message}}
async function init(){const [cfg,sch,status]=await Promise.all([api('/api/v1/config'),api('/api/v1/schema'),api('/api/v1/status')]);state.style=cfg.style;state.styleHash=cfg.styleHash;state.schema=sch;state.nonce=cfg.csrfNonce;$('health').textContent=`${status.production.status} · ${status.lab.bind === '0.0.0.0' ? '192.168.5.3' : status.lab.bind}:${status.lab.port}`;$('facts').innerHTML=`<span>engine <b>${status.engine}</b></span><span>model <b>${status.model}</b></span><span>OminiX <b>${status.ominixRevision.slice(0,12)}</b></span><span>profile <b>${status.profile}</b></span><span>style <b>${status.styleHash.slice(0,12)}</b></span><span>release <b>${status.releaseVersion}</b></span>`;$('emotion').replaceChildren(...Object.keys(state.style.emotions).map(e=>{const o=document.createElement('option');o.value=e;o.textContent=e;return o}));$('emotion').addEventListener('change',fillEmotion);$('baseline').addEventListener('input',()=>{updatePreview();renderSlots()});$('delta').addEventListener('input',()=>{updatePreview();renderSlots()});$('text').addEventListener('input',()=>{$('count').textContent=`${$('text').value.length} / 1200`;$('textHint').textContent=$('text').value.length<40||$('text').value.length>90?'Try 40–90 Japanese characters for routine comparisons.':'Good routine comparison length.'});$('reset').addEventListener('click',fillEmotion);$('generate').addEventListener('click',generate);$('draft').addEventListener('click',saveDraft);$('proposal').addEventListener('click',createProposal);$('refresh').addEventListener('click',async()=>renderResults((await api('/api/v1/history')).items));renderControls();fillEmotion();$('text').dispatchEvent(new Event('input'))}
window.addEventListener('error',e=>{$('health').textContent=e.message});init().catch(e=>{$('health').textContent=e.message});
