name: dashdot

services:
  dashdot:
    image: mauricenino/dashdot:latest
    pull_policy: never
    container_name: dashdot
    restart: always
    ports:
      - "${DASHDOT_PORT:-0.0.0.0:3001}:3001"
    volumes:
      - /:/mnt/host:ro
    x-casaos:
      author: self
      category: Utilities
      port_map: "3001"
      scheme: http
      title:
        custom: dashdot
