#!/usr/bin/env bash

# Shared host profile for deploy, doctor, bootstrap and Operation Skuld checks.
# A real profile is local-only; this file contains safe defaults and no secret.
amadeus_host_profile_load() {
  local profile_root="${1:?repository root is required}"
  local profile_file="${AMADEUS_HOST_PROFILE:-$profile_root/infra/host-profile.env}"
  if [[ -f "$profile_file" ]]; then
    # shellcheck disable=SC1090
    source "$profile_file"
  fi

  ORBSTACK_MACHINE="${ORBSTACK_MACHINE:-ubuntu}"
  OPENCLAW_APP_DIR="${OPENCLAW_APP_DIR:-/var/lib/casaos/apps/openclaw}"
  OPENCLAW_DATA_DIR="${OPENCLAW_DATA_DIR:-/DATA/AppData/openclaw}"
  RADAR_APP_DIR="${RADAR_APP_DIR:-/var/lib/casaos/apps/product-radar}"
  RADAR_DATA_DIR="${RADAR_DATA_DIR:-/DATA/AppData/product-radar}"
  AMADEUS_NETWORK_NAME="${AMADEUS_NETWORK_NAME:-amadeus_network}"
  NINE_ROUTER_NETWORK_NAME="${NINE_ROUTER_NETWORK_NAME:-9router_default}"
  NINE_ROUTER_IMAGE="${NINE_ROUTER_IMAGE:-local/9router:0.5.81}"
  MEDIA_ADAPTER_APP_DIR="${MEDIA_ADAPTER_APP_DIR:-/var/lib/casaos/apps/media-organizer-adapter}"
  MEDIA_ADAPTER_CONTAINER="${MEDIA_ADAPTER_CONTAINER:-media-organizer-adapter}"
  MAC_CONTROL_HOST="${MAC_CONTROL_HOST:-host.docker.internal}"
  MAC_CONTROL_USER="${MAC_CONTROL_USER:-$(id -un)}"
  MAC_CONTROL_KEY_HOST_FILE="${MAC_CONTROL_KEY_HOST_FILE:-$OPENCLAW_DATA_DIR/secrets/mac-ssh-key}"
  HOME_LAB_HOST="${HOME_LAB_HOST:-http://host.docker.internal}"
  HOME_LAB_BASE_URL="${HOME_LAB_BASE_URL:-$HOME_LAB_HOST}"
  HOME_LAB_GLANCES_URL="${HOME_LAB_GLANCES_URL:-$HOME_LAB_BASE_URL:61208/api/4/quicklook}"
  HOME_LAB_UPTIME_URL="${HOME_LAB_UPTIME_URL:-$HOME_LAB_BASE_URL:61208/api/4/uptime}"
  CONTROL_UI_LAN_ORIGIN="${CONTROL_UI_LAN_ORIGIN:-http://host.docker.internal:18789}"
  EXTERNAL_STORAGE_ROOT="${EXTERNAL_STORAGE_ROOT:-/Volumes/Avalon}"
  EXTERNAL_STORAGE_VOLUME_UUID="${EXTERNAL_STORAGE_VOLUME_UUID:-}"
  EXTERNAL_STORAGE_SENTINEL_ID="${EXTERNAL_STORAGE_SENTINEL_ID:-avalon-primary-8tb}"
  IMMICH_MEDIA_ROOT="${IMMICH_MEDIA_ROOT:-$EXTERNAL_STORAGE_ROOT/immich/data}"
  IMMICH_ENV_FILE="${IMMICH_ENV_FILE:-/DATA/AppData/immich/immich.env}"
  NINE_ROUTER_ENV_FILE="${NINE_ROUTER_ENV_FILE:-/DATA/AppData/9router/9router.env}"
  SKULD_BACKUP_ROOT="${SKULD_BACKUP_ROOT:-$EXTERNAL_STORAGE_ROOT/backups/operation-skuld}"
  STORAGE_WARN_FREE_PERCENT="${STORAGE_WARN_FREE_PERCENT:-20}"
  STORAGE_CRITICAL_FREE_PERCENT="${STORAGE_CRITICAL_FREE_PERCENT:-10}"
  STORAGE_WARN_FREE_BYTES="${STORAGE_WARN_FREE_BYTES:-}"
  STORAGE_CRITICAL_FREE_BYTES="${STORAGE_CRITICAL_FREE_BYTES:-}"
  STORAGE_SAFETY_MARGIN_BYTES="${STORAGE_SAFETY_MARGIN_BYTES:-10737418240}"
  STORAGE_MEANINGFUL_RELEASE_BYTES="${STORAGE_MEANINGFUL_RELEASE_BYTES:-1073741824}"
  STORAGE_GROWTH_HISTORY_RETENTION_DAYS="${STORAGE_GROWTH_HISTORY_RETENTION_DAYS:-90}"
  DOCKER_LOG_DRIVER="${DOCKER_LOG_DRIVER:-local}"
  DOCKER_LOG_MAX_SIZE="${DOCKER_LOG_MAX_SIZE:-20m}"
  DOCKER_LOG_MAX_FILE="${DOCKER_LOG_MAX_FILE:-5}"
  DOCKER_BUILD_CACHE_RETENTION_HOURS="${DOCKER_BUILD_CACHE_RETENTION_HOURS:-168}"
  DEPLOYMENT_IMAGE_RETENTION_COUNT="${DEPLOYMENT_IMAGE_RETENTION_COUNT:-2}"
  DEPLOYMENT_CHECKPOINT_RETENTION_COUNT="${DEPLOYMENT_CHECKPOINT_RETENTION_COUNT:-3}"
  SKULD_SECRET_RECIPIENT="${SKULD_SECRET_RECIPIENT:-}"
  SKULD_SECRET_PASSPHRASE_FILE="${SKULD_SECRET_PASSPHRASE_FILE:-}"
  CODEX_NOTIFY_HOOK_PATH="${CODEX_NOTIFY_HOOK_PATH:-$HOME/.codex/bin/codex-notify.sh}"
  CODEX_NOTIFY_BACKUP_ROOT="${CODEX_NOTIFY_BACKUP_ROOT:-$HOME/.codex/backups}"
  FASHION_SIGLIP_LABEL="${FASHION_SIGLIP_LABEL:-com.productradar.fashion-siglip}"
  FASHION_SIGLIP_PORT="${FASHION_SIGLIP_PORT:-18400}"
  FASHION_SIGLIP_INSTALL_DIR="${FASHION_SIGLIP_INSTALL_DIR:-$HOME/Library/Application Support/ProductRadar/FashionSigLIP}"
  FASHION_SIGLIP_MODEL_CACHE_DIR="${FASHION_SIGLIP_MODEL_CACHE_DIR:-$FASHION_SIGLIP_INSTALL_DIR/models/huggingface}"
  FASHION_SIGLIP_MODEL_CACHE_POLICY="${FASHION_SIGLIP_MODEL_CACHE_POLICY:-redownload}"

  export ORBSTACK_MACHINE OPENCLAW_APP_DIR OPENCLAW_DATA_DIR RADAR_APP_DIR RADAR_DATA_DIR
  export AMADEUS_NETWORK_NAME NINE_ROUTER_NETWORK_NAME NINE_ROUTER_IMAGE MEDIA_ADAPTER_APP_DIR MEDIA_ADAPTER_CONTAINER
  export MAC_CONTROL_HOST MAC_CONTROL_USER MAC_CONTROL_KEY_HOST_FILE
  export HOME_LAB_HOST HOME_LAB_BASE_URL HOME_LAB_GLANCES_URL HOME_LAB_UPTIME_URL CONTROL_UI_LAN_ORIGIN
  export EXTERNAL_STORAGE_ROOT EXTERNAL_STORAGE_VOLUME_UUID EXTERNAL_STORAGE_SENTINEL_ID IMMICH_MEDIA_ROOT IMMICH_ENV_FILE NINE_ROUTER_ENV_FILE SKULD_BACKUP_ROOT
  export STORAGE_WARN_FREE_PERCENT STORAGE_CRITICAL_FREE_PERCENT STORAGE_WARN_FREE_BYTES STORAGE_CRITICAL_FREE_BYTES STORAGE_SAFETY_MARGIN_BYTES
  export STORAGE_MEANINGFUL_RELEASE_BYTES STORAGE_GROWTH_HISTORY_RETENTION_DAYS DOCKER_LOG_DRIVER DOCKER_LOG_MAX_SIZE DOCKER_LOG_MAX_FILE
  export DOCKER_BUILD_CACHE_RETENTION_HOURS DEPLOYMENT_IMAGE_RETENTION_COUNT DEPLOYMENT_CHECKPOINT_RETENTION_COUNT
  export SKULD_SECRET_RECIPIENT SKULD_SECRET_PASSPHRASE_FILE
  export CODEX_NOTIFY_HOOK_PATH CODEX_NOTIFY_BACKUP_ROOT
  export FASHION_SIGLIP_LABEL FASHION_SIGLIP_PORT FASHION_SIGLIP_INSTALL_DIR FASHION_SIGLIP_MODEL_CACHE_DIR
  export FASHION_SIGLIP_MODEL_CACHE_POLICY
  export AMADEUS_HOST_PROFILE_FILE="$profile_file"
}
