name: ariang

services:
  ariang:
    image: p3terx/ariang:latest
    pull_policy: never
    container_name: ariang
    restart: always
    ports:
      - "${ARIANG_PORT:-0.0.0.0:6880}:6880"
    x-casaos:
      author: self
      category: Utilities
      port_map: "6880"
      scheme: http
      title:
        custom: ariang
